### ISSUE TITLE
Caffe descriptor generator dies on invalid images

### ISSUE THREAD

**Issue by danlamanna** [Kitware/SMQTK#283] opened 2016-11-11 20:18 UTC
Most things are handled with try/except blocks, but images that pass tika checks can still be considered invalid by `PIL.Image` for reasons other than truncation. I'm going to try to look into this.

**Comment by Purg** [comment] 2017-11-17 23:22
Is this still relevant given changes since last year?  We can close this issue unless you have something to reproduce the issue given the current codebase.

**Closed** 2023-03-14 14:40 UTC
